### ISSUE TITLE
Mention SDK generation approaches 

### ISSUE THREAD

**Issue by dannysheridan** [PradeepLoganathan/pradeepl-blog#45]
Hey Pradeep, 

up to refresh this post: https://pradeepl.com/blog/openapi-specification-swagger/ by adding popular options for generating SDKs from OpenAPI?

fwiw: I’m a core maintainer of Fern (https://github.com/fern-api/fern) which delivers SDKs and API docs. Encourage you to check out openapi-generator and fern generators.

**Comment by PradeepLoganathan** [comment]
Hello @dannysheridan 

Thanks for the heads up. I am happy for you to add a section about how developers can use REST API's to generate SDK's/documentation. You can add fern as a means of doing this and add in links to learn more. If you could do this and generate a pull request.. I will review and merge for sure. Happy to help you through this process.

**Comment by dannysheridan** [comment]
Rad- added! Lmk what you think: https://github.com/PradeepLoganathan/pradeepl-blog/pull/53

**Comment by PradeepLoganathan** [comment]
Merged
